job('First-Maven-Project-Via-DSL') {
    description("First Maven job generated by the DSL on ${new Date()}")
    scm {
        git("https://github.com/lilitagetes/studyhard.git", "*/Labs")
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('package', 'Lab3_4/pom.xml')
    }
    publishers {
        atchiveArtfacats('**/*.jar')
    }
}
