pipeline {
    agent any
    stages {
        stage('Build App') {
            steps {
                sh 'mvn -f pom.xml clean package'
            }
            post {
                success {
                    echo "Archiving the Artifacts..."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }

        stage('Create Project Docker Image') {
            steps {
                sh "docker build . -t tomcatsamplewebapp:${env.BUILD_ID}"
            }
        }
    }
}
